blank_issues_enabled: true
contact_links:
  - name: Support questions ğŸ’¬
    url: https://github.com/orgs/turath-project/discussions
    about: Find announcements, discussions, recipes and much more in the Turath Discussions.
  - name: Propose a change to TÅ«rath ğŸ“
    url: https://github.com/turath-project/rfcs/
    about: Would you like to propose a change to Turath? RFC is what you are looking for!
